### ISSUE TITLE
Price addition: display current number of prices already inputted

### ISSUE THREAD

**Issue by serpico** [openfoodfacts/open-prices-frontend#1071]
### Problem
Since we now ask the total number of products on the receipt as well as the total amount/price it could be nice to have the number of prices already inputted displayed and updated for the user to compare keep track of...

### Proposed solution
Maybe "slide" this value under the last product inputted and above Nouveau prix ( see screenshot ) ...Although it's a bit far from the above mentioned value of  the total number of products on the receipt currently displayed a the bottom left of the page, as a chip, but it's where the line of sight of the user would be, where the last user operation is updated, IMHO

![Image](https://github.com/user-attachments/assets/c717fd1e-fb65-4667-8ff6-7da2ed97f69e)

**Comment by raphodn** [comment]
Kinda linked : I did a PR today - https://github.com/openfoodfacts/open-prices-frontend/pull/1072 - that scrolls to the "New price" form. On mobile, the count is pretty much never visible in the end, you have to scroll above to see it. It could be an [expansion panel](https://vuetifyjs.com/en/components/expansion-panels/#usage) with just the count visible, but having a confirmation that the last price has effectively been added seems somthing to keep.

So it could be put in the footer of that "already added" card. Both the current "X prices already uploaded" and an extra "X prices already uploaded (of Y)" if that info is indeed specified.

There will be corned cases (un-managed) where the receipt price count is not exactly the expected number of prices to input : in the case of receipts that list duplicate products instead of having a count column (example [here](https://prices.openfoodfacts.org/img/0021/1y6G281zUN.webp))

**Comment by raphodn** [comment]
@serpico let me know once you test it :)

**Comment by serpico** [comment]
it looks good !!! no complaint :-)
