### ISSUE TITLE
Add a dark mode

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#274]
### Story

Add a toggle to switch the UI to dark mode
- remember the user choice
- depending on browser/device settings ?

**Comment by psankhe28** [comment]
Apologies, @raphodn, I accidentally force-pushed. Additionally, I'm sorry for the delayed contribution to this pull request due to academic commitments. I have a question regarding the toggle button, as pointed out by teolomon. It's supposed to be in the settings, but I'm having trouble locating it. Can you provide some guidance on this matter?

I'm uncertain if you'll receive a notification or be able to view the comment on a closed pull request, so I'm reaching out here.

**Comment by raphodn** [comment]
Vuetify has a "dark" theme : https://vuetifyjs.com/en/features/theme/#setup

**Comment by raphodn** [comment]
A possible better version would be to select between 3 options: Light, Dark and System.

Example in https://vuetifyjs.com/en/ : 
![image](https://github.com/user-attachments/assets/e3459f55-6274-412b-940c-cc4252503cae)
