### ISSUE TITLE
Mismatch between language list & crowdin locales

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#277]
### Story

The file `i18n/data/languages.json` has a list of languages, but their code don't all correspond to the (official ?) crowdIn locale list (in `i18n/locales/...`).
This list of languages is also used to generate the category translations...

This list of languages was generated in #241 from https://github.com/annexare/Countries/blob/main/packages/countries/src/data/languages.ts

**Comment by dq18** [comment]
@raphodn I can add a library that gets the user location (country) by IP and then automatically select the country.
However, I think it will be better to have an onboarding page, basically bringing up the Settings page the first time a user logs in the app. What do you think?

**Comment by raphodn** [comment]
The issue here is first and foremost about improving the "language selector" in the user settings, to match it with the full list provided by crowdin.

I think a country selector is something different, and should be done in another issue..

**Comment by dq18** [comment]
I edited the story you created to explain why I need to the country selector and tasks. Maybe you did not see the change.

Crowdin generates locales with format like `nl-NL.json` . If I improve the language selector right away it will disable a few languages like nl, pt, zh, sr.
For 'en', since it is our template default, it is not an issue, though `en-GB.json, en-AU.json` will never be used.
We have `nl.json` and 'pt.json' that were originally created by me but not updated by Crowdin and will need to be removed

**Comment by raphodn** [comment]
Also, en / en-GB / en-AU actually correspond to different languages ^^

for example : the wikipedia language selector in the account settings
![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/f6998f87-438b-4f6d-907c-d30a81ab2d67)

**Comment by raphodn** [comment]
Todo : script to auto-generate the languages.json
- use crowdin list as input
- find a full list of languages (Didier used https://github.com/annexare/Countries/blob/main/packages/countries/src/data/languages.ts)
- fields : code, name, native
