### ISSUE TITLE
Users should not be able to login with their email (username only)

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#947]
### What

We should not allow users to login with their email.
We currently only manage the username.
- show an error message if an email is used

### Linked issues

#571

**Comment by TTalex** [comment]
I've noticed that my acces_token always takes the following shape: `<username>__U<uuid>`, even when I use an email as login.

If this is true, maybe a better solution would be to parse this access token, extract the username and feed it to the appStore instead of what the user put in the signin form ?

Something like this #956 seems to work for me.

**Comment by raphodn** [comment]
I renamed the issue & description, thanks for the work Alex !
