### ISSUE TITLE
We can't read any more from receipts due to poor quality

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/open-prices-frontend#952]
Following #924

On the web version, the switch to images of size 400px made it impossible to read for most receipts.

I would suggest to:

- display the full version when you're on the price addition form
- in other cases, open a modal when clicking on a proof image to display proof full size.

**Comment by TTalex** [comment]
I would argue for another approach: the only place we want proofs to be thumbnails is on the UserDashboardProofList page, where many proofs might be loaded.

Everywhere else, details are important, and only one proof is displayed.

There might be an arguments for thumbnails on the AddPriceMultiple page, when selecting a recent proof, but since only 10 proofs are displayed, and their content is relevant for choice, I believe they should also be high-def.

Here's a summary of pages displaying proofs
| Page | How | How many proofs | Is detail important |
| --- | --- |  --- | --- |
| UserDashboardProofList | - | Many / All | Not really |
| AddPrice | Adding prices to a proof | 1 | Yes |
| AddPrice | Selecting a recent proof | 10 | Sure |
| Pages with a Price Card | Click on the proof btn | 1 | Yes |
| ProofDetail | - | 1 | Sure |
| ProofEditDialog | - | 1 | Yes |
| ProofDeleteDialog | - | 1 | Yes |

Proposed implementation: #955
